version: '3'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SERVICE_NAME: ${VITE_SERVICE_NAME}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_KEY: ${VITE_SUPABASE_KEY}
    ports:
      - "8080:8080"
